/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relaxvian;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayas
 */
public class Bot extends javax.swing.JFrame {

    /**
     * Creates new form Bot
     */
    // public static String server = "", username = "", password = "";
    private static queue GameQueue;
    private static String currentVillage;

    public Bot() throws IOException, Exception {

        initComponents();
        GameQueue = new queue();
        this.currentVillage = Login.htmlBrowser.getVillageInfo().get(0);
        for (int i = 0; i < Login.htmlBrowser.getVillageInfo().size(); i++) {
            this.selectVillage.addItem(Login.htmlBrowser.getVillageInfo().get(i));
        }
        this.showVil.setText(currentVillage);

    }

    public static JTable getFarmList() {
        return FarmList;
    }

    public static String getCurVillage() {
        return currentVillage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        LogPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        f_14 = new javax.swing.JLabel();
        f_3 = new javax.swing.JLabel();
        f_8 = new javax.swing.JLabel();
        f_1 = new javax.swing.JLabel();
        f_9 = new javax.swing.JLabel();
        f_7 = new javax.swing.JLabel();
        f_13 = new javax.swing.JLabel();
        f_11 = new javax.swing.JLabel();
        f_18 = new javax.swing.JLabel();
        f_17 = new javax.swing.JLabel();
        f_10 = new javax.swing.JLabel();
        f_12 = new javax.swing.JLabel();
        f_15 = new javax.swing.JLabel();
        f_16 = new javax.swing.JLabel();
        f_6 = new javax.swing.JLabel();
        f_4 = new javax.swing.JLabel();
        f_5 = new javax.swing.JLabel();
        f_2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selectVillage = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        showVil = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        f_40 = new javax.swing.JLabel();
        f_39 = new javax.swing.JLabel();
        f_38 = new javax.swing.JLabel();
        f_37 = new javax.swing.JLabel();
        f_36 = new javax.swing.JLabel();
        f_35 = new javax.swing.JLabel();
        f_34 = new javax.swing.JLabel();
        f_33 = new javax.swing.JLabel();
        f_32 = new javax.swing.JLabel();
        f_22 = new javax.swing.JLabel();
        f_31 = new javax.swing.JLabel();
        f_30 = new javax.swing.JLabel();
        f_29 = new javax.swing.JLabel();
        f_28 = new javax.swing.JLabel();
        f_27 = new javax.swing.JLabel();
        f_26 = new javax.swing.JLabel();
        f_25 = new javax.swing.JLabel();
        f_24 = new javax.swing.JLabel();
        f_23 = new javax.swing.JLabel();
        f_21 = new javax.swing.JLabel();
        f_20 = new javax.swing.JLabel();
        f_19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        barrackID = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        troopsEvery = new javax.swing.JComboBox();
        unitType2 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        unitType = new javax.swing.JComboBox();
        TroopAmmount = new javax.swing.JTextField();
        FarmID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        sendTime = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        buildingQueues = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        FarmList = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Logs = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        command = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relaxvian");

        LogPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setLayout(null);

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setLayout(null);

        f_14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f_14.setText("14");
        f_14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_14MouseClicked(evt);
            }
        });
        jPanel9.add(f_14);
        f_14.setBounds(160, 190, 40, 30);

        f_3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_3.setText("    3 ");
        f_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_3MouseClicked(evt);
            }
        });
        jPanel9.add(f_3);
        f_3.setBounds(230, 50, 30, 30);

        f_8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_8.setText("   8");
        f_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_8MouseClicked(evt);
            }
        });
        jPanel9.add(f_8);
        f_8.setBounds(40, 120, 30, 30);

        f_1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_1.setText("   1");
        f_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_1MouseClicked(evt);
            }
        });
        jPanel9.add(f_1);
        f_1.setBounds(110, 40, 30, 30);

        f_9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_9.setText("   9");
        f_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_9MouseClicked(evt);
            }
        });
        jPanel9.add(f_9);
        f_9.setBounds(90, 110, 30, 40);

        f_7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_7.setText("   7");
        f_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_7MouseClicked(evt);
            }
        });
        jPanel9.add(f_7);
        f_7.setBounds(270, 90, 40, 30);

        f_13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_13.setText("  13");
        f_13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_13MouseClicked(evt);
            }
        });
        jPanel9.add(f_13);
        f_13.setBounds(100, 170, 30, 30);

        f_11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f_11.setText("11");
        f_11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_11MouseClicked(evt);
            }
        });
        jPanel9.add(f_11);
        f_11.setBounds(270, 140, 40, 50);

        f_18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f_18.setText("18");
        f_18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_18MouseClicked(evt);
            }
        });
        jPanel9.add(f_18);
        f_18.setBounds(190, 240, 40, 30);

        f_17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_17.setText(" 17");
        f_17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_17MouseClicked(evt);
            }
        });
        jPanel9.add(f_17);
        f_17.setBounds(150, 230, 30, 40);

        f_10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f_10.setText("10");
        f_10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_10MouseClicked(evt);
            }
        });
        jPanel9.add(f_10);
        f_10.setBounds(210, 130, 50, 60);

        f_12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_12.setText("   12");
        f_12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_12MouseClicked(evt);
            }
        });
        jPanel9.add(f_12);
        f_12.setBounds(50, 170, 30, 40);

        f_15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f_15.setText("15");
        f_15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_15MouseClicked(evt);
            }
        });
        jPanel9.add(f_15);
        f_15.setBounds(240, 210, 40, 20);

        f_16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_16.setText(" 16");
        f_16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_16MouseClicked(evt);
            }
        });
        jPanel9.add(f_16);
        f_16.setBounds(100, 220, 30, 30);

        f_6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_6.setText("   6 ");
        f_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_6MouseClicked(evt);
            }
        });
        jPanel9.add(f_6);
        f_6.setBounds(210, 100, 40, 30);

        f_4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f_4.setText("    4 ");
        f_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        f_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_4MouseClicked(evt);
            }
        });
        jPanel9.add(f_4);
        f_4.setBounds(40, 70, 40, 30);

        f_5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_5.setText("     5 ");
        f_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_5MouseClicked(evt);
            }
        });
        jPanel9.add(f_5);
        f_5.setBounds(140, 80, 40, 30);

        f_2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f_2.setText("    2");
        f_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_2MouseClicked(evt);
            }
        });
        jPanel9.add(f_2);
        f_2.setBounds(170, 40, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resources/f3.png"))); // NOI18N
        jPanel9.add(jLabel5);
        jLabel5.setBounds(20, 20, 300, 264);

        jLabel4.setText("Click resource tile to add to the queue");
        jPanel9.add(jLabel4);
        jLabel4.setBounds(70, 290, 240, 14);

        jPanel4.add(jPanel9);
        jPanel9.setBounds(10, 40, 350, 320);

        jPanel4.add(selectVillage);
        selectVillage.setBounds(370, 70, 120, 20);

        jLabel1.setText("choose a village");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(380, 50, 100, 14);

        jButton1.setText("Change village");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(370, 100, 120, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Current village: ");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 10, 160, 30);

        showVil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        showVil.setForeground(new java.awt.Color(0, 153, 255));
        showVil.setText("Your village");
        jPanel4.add(showVil);
        showVil.setBounds(140, 10, 260, 30);

        jButton2.setText("Upgrade all ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(370, 310, 110, 23);

        jButton4.setText("Reset village");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(370, 280, 110, 23);

        jButton8.setText("Relogin");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(370, 220, 110, 23);

        jTabbedPane1.addTab("Resource Tiles", jPanel4);

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel15.setLayout(null);

        f_40.setText("   ");
        f_40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_40MouseClicked(evt);
            }
        });
        jPanel15.add(f_40);
        f_40.setBounds(160, 270, 90, 14);

        f_39.setText("   ");
        f_39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_39MouseClicked(evt);
            }
        });
        jPanel15.add(f_39);
        f_39.setBounds(270, 140, 30, 20);

        f_38.setText("   ");
        f_38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_38MouseClicked(evt);
            }
        });
        jPanel15.add(f_38);
        f_38.setBounds(240, 240, 20, 14);

        f_37.setText("   ");
        f_37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_37MouseClicked(evt);
            }
        });
        jPanel15.add(f_37);
        f_37.setBounds(150, 230, 20, 14);

        f_36.setText("   ");
        f_36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_36MouseClicked(evt);
            }
        });
        jPanel15.add(f_36);
        f_36.setBounds(250, 210, 20, 14);

        f_35.setText("   ");
        f_35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_35MouseClicked(evt);
            }
        });
        jPanel15.add(f_35);
        f_35.setBounds(170, 210, 20, 14);

        f_34.setText("   ");
        f_34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_34MouseClicked(evt);
            }
        });
        jPanel15.add(f_34);
        f_34.setBounds(300, 190, 20, 14);

        f_33.setText("   ");
        f_33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_33MouseClicked(evt);
            }
        });
        jPanel15.add(f_33);
        f_33.setBounds(220, 180, 10, 10);

        f_32.setText("   ");
        f_32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_32MouseClicked(evt);
            }
        });
        jPanel15.add(f_32);
        f_32.setBounds(110, 180, 20, 14);

        f_22.setText("   ");
        f_22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_22MouseClicked(evt);
            }
        });
        jPanel15.add(f_22);
        f_22.setBounds(280, 60, 30, 20);

        f_31.setText("   ");
        f_31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_31MouseClicked(evt);
            }
        });
        jPanel15.add(f_31);
        f_31.setBounds(340, 170, 20, 14);

        f_30.setText("   ");
        f_30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_30MouseClicked(evt);
            }
        });
        jPanel15.add(f_30);
        f_30.setBounds(160, 150, 20, 10);

        f_29.setText("   ");
        f_29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_29MouseClicked(evt);
            }
        });
        jPanel15.add(f_29);
        f_29.setBounds(190, 130, 20, 14);

        f_28.setText("   ");
        f_28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_28MouseClicked(evt);
            }
        });
        jPanel15.add(f_28);
        f_28.setBounds(100, 150, 20, 14);

        f_27.setText("   ");
        f_27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_27MouseClicked(evt);
            }
        });
        jPanel15.add(f_27);
        f_27.setBounds(330, 130, 20, 14);

        f_26.setText("   ");
        f_26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_26MouseClicked(evt);
            }
        });
        jPanel15.add(f_26);
        f_26.setBounds(230, 100, 20, 14);

        f_25.setText("   ");
        f_25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_25MouseClicked(evt);
            }
        });
        jPanel15.add(f_25);
        f_25.setBounds(170, 110, 20, 14);

        f_24.setText("   ");
        f_24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_24MouseClicked(evt);
            }
        });
        jPanel15.add(f_24);
        f_24.setBounds(100, 100, 30, 20);

        f_23.setText("   ");
        f_23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_23MouseClicked(evt);
            }
        });
        jPanel15.add(f_23);
        f_23.setBounds(320, 100, 40, 20);

        f_21.setText("   ");
        f_21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_21MouseClicked(evt);
            }
        });
        jPanel15.add(f_21);
        f_21.setBounds(220, 50, 30, 20);

        f_20.setText("   ");
        f_20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_20MouseClicked(evt);
            }
        });
        jPanel15.add(f_20);
        f_20.setBounds(180, 50, 30, 20);

        f_19.setText("   ");
        f_19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f_19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_19MouseClicked(evt);
            }
        });
        jPanel15.add(f_19);
        f_19.setBounds(130, 70, 30, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png"))); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(400, 323));
        jPanel15.add(jLabel10);
        jLabel10.setBounds(40, 10, 390, 290);

        jLabel11.setText("Click on the place you wish to upgrade");
        jPanel15.add(jLabel11);
        jLabel11.setBounds(130, 310, 220, 14);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buildings", jPanel5);

        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barracks.png"))); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        barrackID.setText("Barracks/Stable location");

        jButton5.setText("Add Queue");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        troopsEvery.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30 secs", "60 secs", "90 secs", "120 secs" }));

        unitType2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose unit type", "Legionnaire", "Praetorian", "Imperian", "-", "Equites Imperatoris", "Equites Caesaris", "-", "-", "-", "-", "Club Swinger", "Spearman", "Axeman", "-", "Paladin", "Teutonic Knight", "-", "-", "-", "-", "Phalanx", "SwardsMan", "-", "Theutates Thunder", "Druidrider", "Haeduan", "Ram", "cataPult", " " }));

        jButton6.setText("Stop trains");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(unitType2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barrackID)
                        .addGroup(jPanel18Layout.createSequentialGroup()
                            .addComponent(jButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(troopsEvery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(unitType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(barrackID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(troopsEvery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton6))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 136, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Barracks", jPanel6);

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        unitType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose unit type", "Legionnaire", "Praetorian", "Imperian", "-", "Equites Imperatoris", "Equites Caesaris", "-", "-", "-", "-", "Club Swinger", "Spearman", "Axeman", "-", "Paladin", "Teutonic Knight", "-", "-", "-", "-", "Phalanx", "SwardsMan", "-", "Theutates Thunder", "Druidrider", "Haeduan" }));

        TroopAmmount.setText("Ammount of troops");

        FarmID.setText("Farm Village ID");

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        sendTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Send every", "1 min", "2 min", "3 min", "4 min", "5 min", "6 min", "7 min", "8 min", "9 min", "10 min", "11 min", "12 min", "13 min", "14 min", "15 min", "16 min", "17 min", "18 min", "19 min", "20 min", "21 min", "22 min", "23 min", "24 min", "25 min", "26 min", "27 min", "28 min", "29 min", "30 min" }));

        jLabel6.setText("Please Note:");

        jLabel7.setText("Inputing wronge village id or units that do not belong ");

        jLabel8.setText("with your tribe or an ammount of troops that you do");

        jLabel9.setText(" not have will make the program skip the farm");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(unitType, 0, 147, Short.MAX_VALUE)
                        .addComponent(TroopAmmount)
                        .addComponent(FarmID))
                    .addComponent(jButton3)
                    .addComponent(sendTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unitType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TroopAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FarmID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Farm", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Send Resources to Capital", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        LogPanel.addTab("Village", jPanel1);

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        buildingQueues.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Field/Building id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        buildingQueues.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(buildingQueues);
        if (buildingQueues.getColumnModel().getColumnCount() > 0) {
            buildingQueues.getColumnModel().getColumn(0).setResizable(false);
        }

        jToggleButton1.setText("Delete");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Building/resource tile queues", jPanel11);

        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        FarmList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Farm Id", "Troops", "Troops Id", "Reset time"
            }
        ));
        jScrollPane3.setViewportView(FarmList);

        jToggleButton2.setText("Delete");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton7.setText("Reststart");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(jButton7))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel3.setText("Farm List");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Raid queues/FarmList", jPanel13);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        LogPanel.addTab("Queues", jPanel2);

        Logs.setColumns(20);
        Logs.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Logs.setRows(5);
        Logs.setText(" -----------------Program has Started----------------------");
        Logs.setEnabled(false);
        jScrollPane1.setViewportView(Logs);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        LogPanel.addTab("Logs", jPanel3);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Dont mess with this if you dont know wtf your doing");

        command.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                commandKeyPressed(evt);
            }
        });

        jToggleButton3.setText("Submit Command");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton3)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(command, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(command, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton3)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        LogPanel.addTab("Command line", jPanel16);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Status:");

        status.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        status.setForeground(new java.awt.Color(0, 102, 255));
        status.setText("Stoped");

        jMenu1.setText("File");

        jMenu3.setText("Save Data");

        jMenuItem7.setText("Save Farms for this village");
        jMenu3.add(jMenuItem7);

        jMenuItem10.setText("Save building queues for this village");
        jMenu3.add(jMenuItem10);

        jMenu1.add(jMenu3);

        jMenu4.setText("Load data");

        jMenuItem8.setText("Load Farms for this village");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Load building queues for this village");
        jMenu4.add(jMenuItem9);

        jMenu1.add(jMenu4);

        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("About");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Start/Stop Queues");

        jMenuItem3.setText("Start Queues");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem6.setText("Stop Queues");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(status))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void f_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_1MouseClicked
        GameQueue.AddTile(this.currentVillage + "/1");
        JOptionPane.showMessageDialog(rootPane, "tile 1 Added to queue");

    }//GEN-LAST:event_f_1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.currentVillage = this.selectVillage.getSelectedItem().toString();
        this.showVil.setText(currentVillage);
        GameQueue.UpdateQueues();
        GameQueue.UpdateFarmList();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void f_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_2MouseClicked
        GameQueue.AddTile(this.currentVillage + "/2");
        JOptionPane.showMessageDialog(rootPane, "tile 2 Added to queue");
    }//GEN-LAST:event_f_2MouseClicked

    private void f_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_3MouseClicked
        GameQueue.AddTile(this.currentVillage + "/3");
        JOptionPane.showMessageDialog(rootPane, "tile 3 Added to queue");
    }//GEN-LAST:event_f_3MouseClicked

    private void f_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_4MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/4");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_4MouseClicked

    private void f_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_5MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/5");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");

    }//GEN-LAST:event_f_5MouseClicked

    private void f_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_6MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/6");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_6MouseClicked

    private void f_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_7MouseClicked
        GameQueue.AddTile(this.currentVillage + "/7");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");    }//GEN-LAST:event_f_7MouseClicked

    private void f_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_8MouseClicked
        GameQueue.AddTile(this.currentVillage + "/8");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");    }//GEN-LAST:event_f_8MouseClicked

    private void f_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_9MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/9");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_9MouseClicked

    private void f_10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_10MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/10");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_10MouseClicked

    private void f_11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_11MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/11");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_11MouseClicked

    private void f_12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_12MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/12");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_12MouseClicked

    private void f_13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_13MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/13");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_13MouseClicked

    private void f_14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_14MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/14");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_14MouseClicked

    private void f_15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_15MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/15");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_15MouseClicked

    private void f_16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_16MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/16");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_16MouseClicked

    private void f_17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_17MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/17");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_17MouseClicked

    private void f_18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_18MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/18");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_18MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18");
        JOptionPane.showMessageDialog(rootPane, "All tiles added to queue");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (this.TroopAmmount.getText().length() > 0 && this.FarmID.getText().length()
                > 0 && !this.unitType.getSelectedItem().equals("Choose unit type")
                && !this.sendTime.getSelectedItem().equals("Send every") && !this.unitType.getSelectedItem().equals("-")) {

            try {
                int sendingTime = Integer.parseInt(this.sendTime.getSelectedItem().toString().replaceAll(" min", ""));
                int troopType = this.unitType.getSelectedIndex();
                int zaAmmount = Integer.parseInt(this.TroopAmmount.getText());
                if (this.FarmID.getText().contains(",")){
                    String[] stripper = FarmID.getText().split(",");
                    for (int i = 0; i < stripper.length; i++){
                      GameQueue.AddFarm(new Farm(Integer.parseInt(stripper[i]), zaAmmount, troopType, sendingTime, currentVillage), this.currentVillage);
                                     Bot.log("Farm " + stripper[i] + " added to farm list, raided every " + sendingTime + " mins");

                    }
                }else{
                    int villid = Integer.parseInt(this.FarmID.getText());
                GameQueue.AddFarm(new Farm(villid, zaAmmount, troopType, sendingTime, currentVillage), this.currentVillage);
                                Bot.log("Farm " + villid + " added to farm list, raided every " + sendingTime + " mins");

                }

                JOptionPane.showMessageDialog(rootPane, "Farm added");
            } catch (Exception e) {

                JOptionPane.showMessageDialog(rootPane, "There is an error in your input");

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "There is an error in your input");

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void f_19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_19MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/19");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_19MouseClicked

    private void f_20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_20MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/20");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_20MouseClicked

    private void f_21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_21MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/21");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_21MouseClicked

    private void f_22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_22MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/22");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_22MouseClicked

    private void f_23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_23MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/23");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_23MouseClicked

    private void f_24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_24MouseClicked
        // TODO add your handling code here:
        GameQueue.AddTile(this.currentVillage + "/24");
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }//GEN-LAST:event_f_24MouseClicked
    private void AddTile(String p) {
        GameQueue.AddTile(this.currentVillage + "/" + p);
        JOptionPane.showMessageDialog(rootPane, "Added to queue");
    }
    private void f_25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_25MouseClicked
        // TODO add your handling code here:
        AddTile("25");

    }//GEN-LAST:event_f_25MouseClicked

    private void f_26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_26MouseClicked
        // TODO add your handling code here:
        AddTile("26");
    }//GEN-LAST:event_f_26MouseClicked

    private void f_27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_27MouseClicked
        // TODO add your handling code here:
        AddTile("27");
    }//GEN-LAST:event_f_27MouseClicked

    private void f_28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_28MouseClicked
        // TODO add your handling code here:
        AddTile("28");
    }//GEN-LAST:event_f_28MouseClicked

    private void f_29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_29MouseClicked
        // TODO add your handling code here:
        AddTile("29");
    }//GEN-LAST:event_f_29MouseClicked

    private void f_30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_30MouseClicked
        // TODO add your handling code here:
        AddTile("30");
    }//GEN-LAST:event_f_30MouseClicked

    private void f_31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_31MouseClicked
        // TODO add your handling code here:
        AddTile("31");
    }//GEN-LAST:event_f_31MouseClicked

    private void f_32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_32MouseClicked
        // TODO add your handling code here:
        AddTile("32");
    }//GEN-LAST:event_f_32MouseClicked

    private void f_33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_33MouseClicked
        // TODO add your handling code here:
        AddTile("33");
    }//GEN-LAST:event_f_33MouseClicked

    private void f_34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_34MouseClicked
        // TODO add your handling code here:
        AddTile("34");
    }//GEN-LAST:event_f_34MouseClicked

    private void f_35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_35MouseClicked
        // TODO add your handling code here:
        AddTile("35");
    }//GEN-LAST:event_f_35MouseClicked

    private void f_36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_36MouseClicked
        // TODO add your handling code here:
        AddTile("36");
    }//GEN-LAST:event_f_36MouseClicked

    private void f_37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_37MouseClicked
        // TODO add your handling code here:
        AddTile("37");
    }//GEN-LAST:event_f_37MouseClicked

    private void f_38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_38MouseClicked
        // TODO add your handling code here:
        AddTile("38");
    }//GEN-LAST:event_f_38MouseClicked

    private void f_39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_39MouseClicked
        // TODO add your handling code here:
        AddTile("39");
    }//GEN-LAST:event_f_39MouseClicked

    private void f_40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_40MouseClicked
        // TODO add your handling code here:
        AddTile("40");
    }//GEN-LAST:event_f_40MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.GameQueue.setStatus(false);
        this.status.setText("Stopped");

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (buildingQueues.getSelectedRows().length != -1 && !GameQueue.getStat()) {
                DefaultTableModel model = (DefaultTableModel) this.buildingQueues.getModel();
                GameQueue.getVillage(currentVillage).getBuilds().remove(buildingQueues.getSelectedRow());
                model.removeRow(buildingQueues.getSelectedRow());
                JOptionPane.showMessageDialog(rootPane, "Field removed !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Please stop the bot first to delete.");

        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (FarmList.getSelectedRows().length != -1 && !GameQueue.getStat()) {
                DefaultTableModel model = (DefaultTableModel) this.FarmList.getModel();
                GameQueue.getVillage(currentVillage).getFarms().remove(FarmList.getSelectedRow());
                model.removeRow(FarmList.getSelectedRow());
                JOptionPane.showMessageDialog(rootPane, "Farm removed!");

            } else {
                JOptionPane.showMessageDialog(rootPane, "Please stop the bot first to delete.");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.GameQueue.setStatus(true);
        this.status.setText("Running");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        GameQueue.setVillageWait(0, currentVillage);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void commandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commandKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_commandKeyPressed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        if (this.command.getText().contains("/upgrade ")) {
            String New = command.getText().replace("/upgrade ", "");
            GameQueue.AddTile(this.currentVillage + "/" + New);

        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (!this.unitType2.getSelectedItem().equals("Choose unit type")) {
            try {
                int place = Integer.parseInt(barrackID.getText());

                GameQueue.getVillage(currentVillage).getTrain().ReNew(barrackID.getText(), 10, this.unitType2.getSelectedIndex() + "");
                Bot.log("Tranings added");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "There is an error in your input");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        GameQueue.getVillage(currentVillage).getTrain().setTraining(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < GameQueue.getVillage(currentVillage).getFarms().size(); i++){
             GameQueue.getVillage(currentVillage).getFarms().get(i).restart();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            // TODO add your handling code here:
            Login.htmlBrowser.loggedout();
        } catch (Exception ex) {
            Logger.getLogger(Bot.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param text
     * @param args the command line arguments
     */
    public static void log(String text) {
        Logs.setText(Logs.getText() + "\n" + text);
    }

    public static queue getQueue() {
        return GameQueue;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FarmID;
    public static javax.swing.JTable FarmList;
    private javax.swing.JTabbedPane LogPanel;
    private static javax.swing.JTextArea Logs;
    private javax.swing.JTextField TroopAmmount;
    private javax.swing.JTextField barrackID;
    public static javax.swing.JTable buildingQueues;
    private javax.swing.JTextField command;
    private javax.swing.JLabel f_1;
    private javax.swing.JLabel f_10;
    private javax.swing.JLabel f_11;
    private javax.swing.JLabel f_12;
    private javax.swing.JLabel f_13;
    private javax.swing.JLabel f_14;
    private javax.swing.JLabel f_15;
    private javax.swing.JLabel f_16;
    private javax.swing.JLabel f_17;
    private javax.swing.JLabel f_18;
    private javax.swing.JLabel f_19;
    private javax.swing.JLabel f_2;
    private javax.swing.JLabel f_20;
    private javax.swing.JLabel f_21;
    private javax.swing.JLabel f_22;
    private javax.swing.JLabel f_23;
    private javax.swing.JLabel f_24;
    private javax.swing.JLabel f_25;
    private javax.swing.JLabel f_26;
    private javax.swing.JLabel f_27;
    private javax.swing.JLabel f_28;
    private javax.swing.JLabel f_29;
    private javax.swing.JLabel f_3;
    private javax.swing.JLabel f_30;
    private javax.swing.JLabel f_31;
    private javax.swing.JLabel f_32;
    private javax.swing.JLabel f_33;
    private javax.swing.JLabel f_34;
    private javax.swing.JLabel f_35;
    private javax.swing.JLabel f_36;
    private javax.swing.JLabel f_37;
    private javax.swing.JLabel f_38;
    private javax.swing.JLabel f_39;
    private javax.swing.JLabel f_4;
    private javax.swing.JLabel f_40;
    private javax.swing.JLabel f_5;
    private javax.swing.JLabel f_6;
    private javax.swing.JLabel f_7;
    private javax.swing.JLabel f_8;
    private javax.swing.JLabel f_9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JComboBox selectVillage;
    private javax.swing.JComboBox sendTime;
    private javax.swing.JLabel showVil;
    public static javax.swing.JLabel status;
    private javax.swing.JComboBox troopsEvery;
    private javax.swing.JComboBox unitType;
    private javax.swing.JComboBox unitType2;
    // End of variables declaration//GEN-END:variables
}
